# Set up your streams to rtsp here.
port: "8554"
streams: # Cannot rename - must leave this as is.

  # stream-cam:
  #   type: cam
  #   source: v4l2src device=/dev/video0
  #   mountpoint: /cam
  #   format: video/x-raw,width=640,height=480
  #   encoder: omxh264enc

  stream-raw:
    type: topic
    source: /camera/image_raw
    mountpoint: /raw
    format: video/x-raw,width=800,height=600
    encoder: omxh264enc

  stream-dashboard:
    type: topic
    source: /dashboard
    mountpoint: /dashboard
    format: video/x-raw,width=800,height=600
    encoder: omxh264enc


